# Generated by Django 4.1.1 on 2022-11-15 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('cords_lat', models.FloatField()),
                ('cords_long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sd', models.IntegerField(blank=True, null=True)),
                ('assessor_number', models.IntegerField(blank=True, null=True)),
                ('owner_of_record', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_bill', models.CharField(blank=True, max_length=50, null=True)),
                ('res_units', models.IntegerField(blank=True, null=True)),
                ('comm_units', models.IntegerField(blank=True, null=True)),
                ('prior_year_fire_ambulance_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('total_market_value', models.CharField(blank=True, max_length=50, null=True)),
                ('total_taxable_value', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('real_estate_market_value', models.CharField(blank=True, max_length=50, null=True)),
                ('real_estate_taxable_value', models.CharField(blank=True, max_length=50, null=True)),
                ('property_improvements_market_value', models.CharField(blank=True, max_length=50, null=True)),
                ('property_improvements_taxable_value', models.CharField(blank=True, max_length=50, null=True)),
                ('pp_mkt', models.CharField(blank=True, max_length=50, null=True)),
                ('pp_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('property_location', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('datestamp', models.DateTimeField(blank=True, null=True, verbose_name='%Y%m%d')),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('cords_lat', models.FloatField()),
                ('cords_long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='input_files')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='output_files')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('fire_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiteFish.firestation')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiteFish.home')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whiteFish.inputfile')),
                ('output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whiteFish.outputfile')),
            ],
        ),
    ]
