# Generated by Django 4.1.1 on 2022-11-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteFish', '0101_remove_firestation_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
